# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.currencyListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.currencyListWidget.setGeometry(QtCore.QRect(20, 60, 256, 311))
        self.currencyListWidget.setObjectName("currencyListWidget")
        self.currencyLabel = QtWidgets.QLabel(self.centralwidget)
        self.currencyLabel.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currencyLabel.setFont(font)
        self.currencyLabel.setObjectName("currencyLabel")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 410, 251, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dailyCheckBox = QtWidgets.QCheckBox(self.frame)
        self.dailyCheckBox.setGeometry(QtCore.QRect(10, 10, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dailyCheckBox.setFont(font)
        self.dailyCheckBox.setObjectName("dailyCheckBox")
        self.hourlyCheckBox = QtWidgets.QCheckBox(self.frame)
        self.hourlyCheckBox.setGeometry(QtCore.QRect(10, 40, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hourlyCheckBox.setFont(font)
        self.hourlyCheckBox.setObjectName("hourlyCheckBox")
        self.intervalLabel = QtWidgets.QLabel(self.centralwidget)
        self.intervalLabel.setGeometry(QtCore.QRect(20, 380, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.intervalLabel.setFont(font)
        self.intervalLabel.setObjectName("intervalLabel")
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setGeometry(QtCore.QRect(20, 510, 121, 28))
        self.startPushButton.setObjectName("startPushButton")
        self.unselectedListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.unselectedListWidget.setGeometry(QtCore.QRect(300, 60, 221, 192))
        self.unselectedListWidget.setObjectName("unselectedListWidget")
        self.selectedListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.selectedListWidget.setGeometry(QtCore.QRect(570, 60, 221, 192))
        self.selectedListWidget.setObjectName("selectedListWidget")
        self.logsListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.logsListWidget.setGeometry(QtCore.QRect(290, 300, 501, 241))
        self.logsListWidget.setObjectName("logsListWidget")
        self.logsLlabel = QtWidgets.QLabel(self.centralwidget)
        self.logsLlabel.setGeometry(QtCore.QRect(290, 260, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logsLlabel.setFont(font)
        self.logsLlabel.setObjectName("logsLlabel")
        self.ubselectedLabel = QtWidgets.QLabel(self.centralwidget)
        self.ubselectedLabel.setGeometry(QtCore.QRect(300, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ubselectedLabel.setFont(font)
        self.ubselectedLabel.setObjectName("ubselectedLabel")
        self.selectedLabel = QtWidgets.QLabel(self.centralwidget)
        self.selectedLabel.setGeometry(QtCore.QRect(570, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectedLabel.setFont(font)
        self.selectedLabel.setObjectName("selectedLabel")
        self.selectAllUnselectedPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectAllUnselectedPushButton.setGeometry(QtCore.QRect(530, 120, 31, 28))
        self.selectAllUnselectedPushButton.setObjectName("selectAllUnselectedPushButton")
        self.unselectAllSelectedPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.unselectAllSelectedPushButton.setGeometry(QtCore.QRect(530, 150, 31, 28))
        self.unselectAllSelectedPushButton.setObjectName("unselectAllSelectedPushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.currencyLabel.setText(_translate("MainWindow", "Валюты:"))
        self.dailyCheckBox.setText(_translate("MainWindow", "Дневной интервал"))
        self.hourlyCheckBox.setText(_translate("MainWindow", "Часов интервал"))
        self.intervalLabel.setText(_translate("MainWindow", "Интервал:"))
        self.startPushButton.setText(_translate("MainWindow", "Начать"))
        self.logsLlabel.setText(_translate("MainWindow", "Логи:"))
        self.ubselectedLabel.setText(_translate("MainWindow", "Не выбранные паттерны"))
        self.selectedLabel.setText(_translate("MainWindow", "Выбранные паттерны"))
        self.selectAllUnselectedPushButton.setText(_translate("MainWindow", ">>"))
        self.unselectAllSelectedPushButton.setText(_translate("MainWindow", "<<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
